import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import './theme-config.css';
import { Theme} from '@radix-ui/themes';
import './globals.css';
import NavBar from './NavBar';
import { getServerSession } from 'next-auth';
import { AuthProvider } from './components/SessionProvider';

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
  <AuthProvider session={session}>
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance="light" accentColor="tomato" radius="small" scaling="105%">
          <NavBar />
          <main className='p-5'>{children}</main>
        </Theme>
      </body>
    </html>
    </AuthProvider>

  );
}
